export enum NOTIFICATION_TYPES {
  SYSTEM = 0,
  AVAILABLE = 1,
  NEW_RESERVATION = 2,
  NEW_SELL = 3,
  RESERVATION_CONFIRMATION = 4,
  RESERVATION_REJECTION = 5,
  SELL_CONFIRMATION = 6,
  SELL_REJECTION = 7,
}
